### ISSUE TITLE
ieeetran has an incorrect item "Use of \@item doesn't match its definition"

### ISSUE THREAD

**Issue by DTChuck** [jasedit/simple_templates#1]
Traceback from LaTex output and python output shown below.

Ryans-MacBook-Pro-2:scriptorium ryan$ scriptorium build papers/ieee_paper_test -o ieee_paper
LaTeX conversion failed with the following output:
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./paper.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.
(/Users/ryan/.scriptorium/templates/./simple_templates/ieeetran/setup.tex
(/Users/ryan/.scriptorium/templates/./simple_templates/ieeetran/IEEEtran.cls
Document Class: IEEEtran 2012/11/21 V1.8c by Harald Hanche-Olsen and Anders Chr
istensen
-- Based on V1.7a by Michael Shell
-- See the "IEEEtran_HOWTO" manual for usage information.
-- http://www.michaelshell.org/tex/ieeetran/
(/usr/local/texlive/2015/texmf-dist/tex/latex/psnfss/ot1ptm.fd)
*\* ATTENTION: Single column mode is not typically used with IEEE publications.
-- Using 8.5in x 11in (letter) paper.
-- Using PDF output.
-- This is a 10 point document.
) (/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/local/texlive/2015/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))
(/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/keyval.sty))
(/usr/local/texlive/2015/texmf-dist/tex/latex/url/url.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2015/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/hyperref.cfg))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/local/texlive/2015/texmf-dist/tex/generic/bibtex/apalike.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/tabulary/tabulary.sty
(/usr/local/texlive/2015/texmf-dist/tex/latex/tools/array.sty))
(/usr/local/texlive/2015/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/caption/caption.sty
(/usr/local/texlive/2015/texmf-dist/tex/latex/caption/caption3.sty)

Package caption Warning: Unsupported document class (or package) detected,
(caption)                usage of the caption package is not recommended.
See the caption package documentation for explanation.

) (/usr/local/texlive/2015/texmf-dist/tex/latex/geometry/geometry.sty)
No file paper.aux.
(/usr/local/texlive/2015/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
_geometry_ driver: auto-detecting
_geometry_ detected driver: pdftex
! Use of \@item doesn't match its definition.
<argument> \def \reserved@a {
                             \def \@currenvir {center}\edef \@currenvline {...
l.52 \input{\abstract}

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on paper.log.

Traceback (most recent call last):
  File "/usr/local/bin/scriptorium", line 9, in <module>
    load_entry_point('scriptorium==2.0.0', 'console_scripts', 'scriptorium')()
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/**main**.py", line 102, in main
    args.func(args)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scriptorium-2.0.0-py2.7.egg/scriptorium/**main**.py", line 17, in build_cmd
    shutil.move(pdf, args.output)
  File "/usr/local/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 294, in move
    os.rename(src, real_dst)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by jasedit** [comment]
This looks to be related to a collision with the `\abstract` variable, which has an experimental fix in the fix_variables branch. Test that, and see if it fixes this error

**Comment by DTChuck** [comment]
Cannot reproduce error in the new branch for both #1 and #2. Recommend closing both issues.
