### ISSUE TITLE
Margins incorrect on IEEEtran conference template

### ISSUE THREAD

**Issue by rjgriffin42** [jasedit/simple_templates#12]
The margins and column widths are not correct for ieee conference papers, when setting up `\mycolumns = twocolumn`, `\mydocclass = conference`. 

When lines 41 is commented out, excluding the geometry package, the margins and column widths are correct.

**Comment by jasedit** [comment]
Taking a look at this, the issue is that IEEE defines their own margin variables, that are incompatible with the standard approach. I should have a PR for this shortly.
