### ISSUE TITLE
Extra space before abstract in IEEE papers

### ISSUE THREAD

**Issue by rjgriffin42** [jasedit/simple_templates#18]
There seems to be an extra space placed before the abstract in IEEE papers, whenever the abstract is converted from an mmd to a tex file. This then pushes it onto the next line, throwing the formatting off a little bit.

**Comment by jasedit** [comment]
Do you have an example file for this? My abstract doesn't appear to exhibit this behavior from what I can see

**Comment by rjgriffin42** [comment]
It just does it on my linux machines, not my laptop. Upgrading to the newest version of scriptorium solved this problem, however.
