### ISSUE TITLE
Footenotes have overbars in IEEE conference

### ISSUE THREAD

**Issue by rjgriffin42** [jasedit/simple_templates#20]
Footnotes have overbars in the IEEE conference, when they should not.

**Comment by jasedit** [comment]
Try feat/remove_footnote_rule to test this (I don't know how `\footnoterule` is being overridden, but this might fix it?)

**Comment by rjgriffin42** [comment]
That branch seems to fix it.

**Comment by jasedit** [comment]
Fix merged to master
