### ISSUE TITLE
Reference section is the wrong font size

### ISSUE THREAD

**Issue by rjgriffin42** [jasedit/simple_templates#21]
The reference section is the wrong font size in IEEE template. It is the same font size as the body text, when it should be smaller.

**Comment by jasedit** [comment]
I can't find any explicit reference on how IEEE sets the font size for the reference section. Do you have any code suggestions or examples I could look at?

**Comment by rjgriffin42** [comment]
Honestly, I don't. I think it might be a different between the biblatex ieee format and the actual IEEEtran.bst. As I mentioned on another issue, I generated one using raw tex, and the other using scriptorium, and there is a difference. I'm emailing you the two different papers, so you can see what I'm referring to.

**Comment by jasedit** [comment]
Try feat/shrink_bibliography
