### ISSUE TITLE
Too much space between paragraphs in IEEE conference.

### ISSUE THREAD

**Issue by rjgriffin42** [jasedit/simple_templates#22]
There should not be additional space between paragraphs in the IEEE conference papers.

**Comment by jasedit** [comment]
Do you have a MWE for testing?

**Comment by rjgriffin42** [comment]
I'm not sure what you mean by MWE. I'm comparing to standard IEEE papers visually. I also gutted the standard IEEE `bare_conf.tex`, symlinked to my sections, and included them in that as a shell, and the two visually look different. I think there's also a line spacing difference, but I could be wrong.

**Comment by jasedit** [comment]
Minimum Working Example - something I can throw in a scriptorium setup to test and compare

**Comment by jasedit** [comment]
From my testing with scriptorium, there's something subtle going on with how `\parskip` is set in your example, but it seems to be using the same value. Adding `\parskip 0ex` removes the rubber spacing IEEEtran specifies and uses in both cases, eliminating the spacing in some place, but not changing the length of the paper. Instead, the columns end up slightly more ragged than when the rubber spacing exists.

I can't find anything other than overriding the IEEE formatting to eliminate this - removing biber, dropping a large number of packages, and hard-coding the variable names doesn't seem to have any impact on the spacing. There are some generic references to older versions of IEEEtran exhibiting this problem - have you checked that you don't have an old version installed somewhere?

**Comment by jasedit** [comment]
Is this fixed by using the `ieeeconf` template in #27?

**Comment by rjgriffin42** [comment]
It appears to be!
